server:
    port: 80
spring:
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      cache: false
      servlet:
        content-type: text/html
#  freemarker:
#      cache: false
#      allow-request-override: false
#      check-template-location: true
#      charset: UTF-8
#      content-type: text/html
#      expose-request-attributes: true
#      expose-session-attributes: true
#      expose-spring-macro-helpers: false
#      template-loader-path: classpath:/templates/
#      request-context-attribute: request
#      suffix: .html
  datasource:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/video?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: wangy
      password: 123456
      # \u4F7F\u7528druid\u6570\u636E\u6E90
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

#mybatis:
#  mapper-locations: com.winter.mapping/*.xml
#  type-aliases-package: com.winter.mapper.model


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

